/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as BingoRouteImport } from './routes/bingo'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CartelasRouteImport } from './routes/cartelas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ReceitaRouteImport } from './routes/receita'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const BingoRoute = BingoRouteImport.update({
  id: '/bingo',
  path: '/bingo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CartelasRoute = CartelasRouteImport.update({
  id: '/cartelas',
  path: '/cartelas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitaRoute = ReceitaRouteImport.update({
  id: '/receita',
  path: '/receita',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/bingo': typeof BingoRoute
  '/calendario': typeof CalendarioRoute
  '/cartelas': typeof CartelasRoute
  '/clientes': typeof ClientesRoute
  '/premios': typeof PremiosRoute
  '/produtos': typeof ProdutosRoute
  '/receita': typeof ReceitaRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/bingo': typeof BingoRoute
  '/calendario': typeof CalendarioRoute
  '/cartelas': typeof CartelasRoute
  '/clientes': typeof ClientesRoute
  '/premios': typeof PremiosRoute
  '/produtos': typeof ProdutosRoute
  '/receita': typeof ReceitaRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/bingo': typeof BingoRoute
  '/calendario': typeof CalendarioRoute
  '/cartelas': typeof CartelasRoute
  '/clientes': typeof ClientesRoute
  '/premios': typeof PremiosRoute
  '/produtos': typeof ProdutosRoute
  '/receita': typeof ReceitaRoute
  '/relatorios': typeof RelatoriosRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/bingo'
    | '/calendario'
    | '/cartelas'
    | '/clientes'
    | '/premios'
    | '/produtos'
    | '/receita'
    | '/relatorios'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/bingo'
    | '/calendario'
    | '/cartelas'
    | '/clientes'
    | '/premios'
    | '/produtos'
    | '/receita'
    | '/relatorios'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/bingo'
    | '/calendario'
    | '/cartelas'
    | '/clientes'
    | '/premios'
    | '/produtos'
    | '/receita'
    | '/relatorios'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  BingoRoute: typeof BingoRoute
  CalendarioRoute: typeof CalendarioRoute
  CartelasRoute: typeof CartelasRoute
  ClientesRoute: typeof ClientesRoute
  PremiosRoute: typeof PremiosRoute
  ProdutosRoute: typeof ProdutosRoute
  ReceitaRoute: typeof ReceitaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bingo': {
      id: '/bingo'
      path: '/bingo'
      fullPath: '/bingo'
      preLoaderRoute: typeof BingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartelas': {
      id: '/cartelas'
      path: '/cartelas'
      fullPath: '/cartelas'
      preLoaderRoute: typeof CartelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receita': {
      id: '/receita'
      path: '/receita'
      fullPath: '/receita'
      preLoaderRoute: typeof ReceitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  BingoRoute: BingoRoute,
  CalendarioRoute: CalendarioRoute,
  CartelasRoute: CartelasRoute,
  ClientesRoute: ClientesRoute,
  PremiosRoute: PremiosRoute,
  ProdutosRoute: ProdutosRoute,
  ReceitaRoute: ReceitaRoute,
  RelatoriosRoute: RelatoriosRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
